-- Migration SQL to expand column capacity for AES-256-GCM encrypted fields
-- AES-256-GCM ciphertexts formatted as 'enc:<iv_hex>:<authTag_hex>:<cipher_hex>' require ~70-120 characters minimum.

-- 1. USERS TABLE: Expand financial & sensitive identity columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS secondary_phone VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bank_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_holder VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_number VARCHAR(500) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS upi_id VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pan_number VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gstin VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS aadhaar_masked VARCHAR(255) DEFAULT NULL;

ALTER TABLE users MODIFY COLUMN secondary_phone VARCHAR(255) DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN bank_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN account_holder VARCHAR(255) DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN account_number VARCHAR(500) DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN ifsc_code VARCHAR(255) DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN upi_id VARCHAR(255) DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN pan_number VARCHAR(255) DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN gstin VARCHAR(255) DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN aadhaar_masked VARCHAR(255) DEFAULT NULL;

-- 2. ENROLLMENT_FORMS TABLE: Expand emergency contacts and ID columns
ALTER TABLE enrollment_forms MODIFY COLUMN parent_1_phone VARCHAR(255) DEFAULT NULL;
ALTER TABLE enrollment_forms MODIFY COLUMN parent_2_phone VARCHAR(255) DEFAULT NULL;
ALTER TABLE enrollment_forms MODIFY COLUMN guardian_phone VARCHAR(255) DEFAULT NULL;
ALTER TABLE enrollment_forms MODIFY COLUMN college_id_number VARCHAR(255) DEFAULT NULL;

-- 3. STUDENT_PROFILES TABLE: Expand emergency contacts and ID columns
ALTER TABLE student_profiles MODIFY COLUMN parent_1_phone VARCHAR(255) DEFAULT NULL;
ALTER TABLE student_profiles MODIFY COLUMN parent_2_phone VARCHAR(255) DEFAULT NULL;
ALTER TABLE student_profiles MODIFY COLUMN guardian_phone VARCHAR(255) DEFAULT NULL;
ALTER TABLE student_profiles MODIFY COLUMN college_id_number VARCHAR(255) DEFAULT NULL;
