-- Migration SQL for Owner Bank & Payout Details + Business Information

ALTER TABLE users ADD COLUMN IF NOT EXISTS secondary_phone VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bank_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_holder VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_number VARCHAR(500) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS upi_id VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS business_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS office_address TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(100) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS state VARCHAR(100) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pincode VARCHAR(20) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS operating_since VARCHAR(20) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pan_number VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gstin VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS aadhaar_masked VARCHAR(255) DEFAULT NULL;

-- Modify existing columns if they already exist with shorter lengths
ALTER TABLE users MODIFY COLUMN account_number VARCHAR(500) DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN ifsc_code VARCHAR(255) DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN upi_id VARCHAR(255) DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN pan_number VARCHAR(255) DEFAULT NULL;
ALTER TABLE users MODIFY COLUMN aadhaar_masked VARCHAR(255) DEFAULT NULL;
